### ISSUE TITLE
Collaborative cursors appear offset in Firefox

### ISSUE THREAD

**Issue by joeltg** [pubpub/pubpub-editor#21]
This is a know bug but I think all that's needed to solve it are a few CSS properties:

```css
.collab-cursor { display: inline-block; }
.collab-cursor .inner-bar { bottom: -5px; }
```
